import { Ride, User, Booking, Message } from '../types';

export const currentUser: User = {
  id: 'u0',
  name: 'You',
  rating: 4.9,
  totalRides: 12,
  verified: true,
};

const users: User[] = [
  {
    id: 'u1',
    name: 'Sarah Mitchell',
    rating: 4.8,
    totalRides: 63,
    verified: true,
  },
  {
    id: 'u2',
    name: 'James Chen',
    rating: 4.9,
    totalRides: 41,
    verified: true,
  },
  {
    id: 'u3',
    name: 'Priya Nair',
    rating: 5.0,
    totalRides: 28,
    verified: true,
  },
  {
    id: 'u4',
    name: 'Tom Baker',
    rating: 4.6,
    totalRides: 17,
    verified: false,
  },
  {
    id: 'u5',
    name: 'Emma Kowalski',
    rating: 4.7,
    totalRides: 52,
    verified: true,
  },
];

export const mockRides: Ride[] = [
  {
    id: 'r1',
    driver: users[0],
    tripType: 'intercity',
    fromLocation: 'Wollongong CBD',
    toLocation: 'Sydney Central Station',
    departureTime: nextDayAt('06:30'),
    arrivalEstimateMins: 90,
    pricePerSeat: 20,
    seatsAvailable: 3,
    vehicle: { make: 'Toyota', model: 'Camry', color: 'Silver' },
    luggageNote: 'Small bag + backpack per person',
    notes: 'Leaving from Crown St. Comfortable stop at Heathcote if needed.',
  },
  {
    id: 'r2',
    driver: users[1],
    tripType: 'intercity',
    fromLocation: 'North Wollongong',
    toLocation: 'Sydney Airport (SYD)',
    departureTime: nextDayAt('05:45'),
    arrivalEstimateMins: 95,
    pricePerSeat: 25,
    seatsAvailable: 2,
    vehicle: { make: 'Mazda', model: 'CX-5', color: 'Blue' },
    luggageNote: 'Room for 1 large suitcase each',
    notes: 'Perfect for early flights. I have airport drop-off zone access.',
  },
  {
    id: 'r3',
    driver: users[2],
    tripType: 'intercity',
    fromLocation: 'Parramatta',
    toLocation: 'University of Wollongong',
    departureTime: nextDayAt('15:00'),
    arrivalEstimateMins: 85,
    pricePerSeat: 18,
    seatsAvailable: 4,
    vehicle: { make: 'Hyundai', model: 'i30', color: 'White' },
    luggageNote: 'Backpack only',
    notes: 'Weekly Thursday run. Great for UOW students.',
  },
  {
    id: 'r4',
    driver: users[3],
    tripType: 'intercity',
    fromLocation: 'University of Wollongong',
    toLocation: 'Central Station',
    departureTime: nextDayAt('07:15'),
    arrivalEstimateMins: 80,
    pricePerSeat: 15,
    seatsAvailable: 1,
    vehicle: { make: 'Kia', model: 'Cerato', color: 'Grey' },
    notes: 'Quick trip, no long stops. Cashless only.',
  },
  {
    id: 'r5',
    driver: users[4],
    tripType: 'intercity',
    fromLocation: 'Sydney Central Station',
    toLocation: 'Wollongong CBD',
    departureTime: nextDayAt('18:30'),
    arrivalEstimateMins: 90,
    pricePerSeat: 20,
    seatsAvailable: 3,
    vehicle: { make: 'Subaru', model: 'Outback', color: 'Green' },
    luggageNote: 'Plenty of boot space',
    notes: 'Evening run after work. Happy to drop near your street in Gong.',
  },
  {
    id: 'r6',
    driver: users[1],
    tripType: 'intercity',
    fromLocation: 'Wollongong CBD',
    toLocation: 'Parramatta',
    departureTime: nextDayAt('08:00'),
    arrivalEstimateMins: 100,
    pricePerSeat: 22,
    seatsAvailable: 2,
    vehicle: { make: 'Mazda', model: 'CX-5', color: 'Blue' },
    notes: 'Via M1 toll road, cost split included in fare.',
  },
  {
    id: 'r7',
    driver: users[2],
    tripType: 'intercity',
    fromLocation: 'North Wollongong Station',
    toLocation: 'Sydney Airport (SYD)',
    departureTime: nextDayAt('12:30'),
    arrivalEstimateMins: 95,
    pricePerSeat: 24,
    seatsAvailable: 3,
    vehicle: { make: 'Toyota', model: 'RAV4', color: 'Black' },
    luggageNote: 'Room for skis/board on request',
    notes: 'Midday flight run. Flexible on pickup point along the way.',
  },
  {
    id: 'r8',
    driver: users[0],
    tripType: 'intercity',
    fromLocation: 'Melbourne Southern Cross Station',
    toLocation: 'Geelong city centre',
    departureTime: nextDayAt('09:00'),
    arrivalEstimateMins: 75,
    pricePerSeat: 18,
    seatsAvailable: 3,
    vehicle: { make: 'Holden', model: 'Commodore', color: 'White' },
    luggageNote: 'Medium suitcase ok',
    notes: 'Princes Freeway direct. Pickup near Docklands side of station.',
  },
  {
    id: 'r9',
    driver: users[3],
    tripType: 'intercity',
    fromLocation: 'Geelong city centre',
    toLocation: 'Melbourne Airport (MEL)',
    departureTime: nextDayAt('13:15'),
    arrivalEstimateMins: 70,
    pricePerSeat: 28,
    seatsAvailable: 2,
    vehicle: { make: 'Ford', model: 'Ranger', color: 'Silver' },
    luggageNote: 'Ute tray cover — roomy for bags',
    notes: 'Arvo flight run, Tullamarine terminals 1-4 all covered.',
  },
  {
    id: 'r10',
    driver: users[4],
    tripType: 'intercity',
    fromLocation: 'Brisbane CBD',
    toLocation: 'Gold Coast (Surfers Paradise)',
    departureTime: nextDayAt('16:00'),
    arrivalEstimateMins: 80,
    pricePerSeat: 25,
    seatsAvailable: 3,
    vehicle: { make: 'Toyota', model: 'Kluger', color: 'Black' },
    luggageNote: 'Surfboards welcome',
    notes: 'Friday arvo coastal run down the M1. Aircon is strong.',
  },
  {
    id: 'r11',
    driver: users[1],
    tripType: 'intercity',
    fromLocation: 'Gold Coast (Broadbeach)',
    toLocation: 'Brisbane Airport (BNE)',
    departureTime: nextDayAt('06:00'),
    arrivalEstimateMins: 85,
    pricePerSeat: 30,
    seatsAvailable: 4,
    vehicle: { make: 'Toyota', model: 'Kluger', color: 'Black' },
    luggageNote: 'Room for golf bags',
    notes: 'Early bird airport express. Coffee stop optional at Coomera.',
  },
  {
    id: 'r12',
    driver: users[2],
    tripType: 'local',
    fromLocation: 'Warrawong',
    toLocation: 'Wollongong CBD',
    departureTime: nextDayAt('08:45'),
    arrivalEstimateMins: 15,
    pricePerSeat: 5,
    seatsAvailable: 3,
    vehicle: { make: 'Hyundai', model: 'i30', color: 'White' },
    luggageNote: 'Backpack only',
    notes: 'Daily commute via King St. Westfield Crown St pickup.',
  },
  {
    id: 'r13',
    driver: users[3],
    tripType: 'local',
    fromLocation: 'Shellharbour City Centre',
    toLocation: 'North Wollongong',
    departureTime: nextDayAt('07:30'),
    arrivalEstimateMins: 30,
    pricePerSeat: 7,
    seatsAvailable: 2,
    vehicle: { make: 'Nissan', model: 'X-Trail', color: 'Blue' },
    notes: 'Via the scenic route past Lake Illawarra when traffic is light.',
  },
  {
    id: 'r14',
    driver: users[0],
    tripType: 'local',
    fromLocation: 'Warrawong Plaza',
    toLocation: 'University of Wollongong',
    departureTime: nextDayAt('08:50'),
    arrivalEstimateMins: 20,
    pricePerSeat: 6,
    seatsAvailable: 4,
    vehicle: { make: 'Toyota', model: 'Camry', color: 'Silver' },
    luggageNote: 'Backpack only',
    notes: 'Semester timetable. Drops at UniCentre main gate.',
  },
  {
    id: 'r15',
    driver: users[4],
    tripType: 'local',
    fromLocation: 'Corrimal',
    toLocation: 'Wollongong CBD',
    departureTime: nextDayAt('17:15'),
    arrivalEstimateMins: 15,
    pricePerSeat: 4,
    seatsAvailable: 3,
    vehicle: { make: 'Kia', model: 'Picanto', color: 'Red' },
    notes: 'Homeward bound after work, Princes Hwy straight shot.',
  },
];

export const myBookings: Booking[] = [
  {
    id: 'b1',
    rideId: 'r1',
    passenger: currentUser,
    seatsBooked: 1,
    status: 'confirmed',
    bookedAt: new Date().toISOString(),
  },
];

export const sampleMessages: Message[] = [
  {
    id: 'm1',
    rideId: 'r1',
    senderId: 'u1',
    senderName: 'Sarah Mitchell',
    text: 'Hi! Picking up from the corner of Crown & Keira St — that ok?',
    sentAt: new Date().toISOString(),
  },
  {
    id: 'm2',
    rideId: 'r1',
    senderId: 'u0',
    senderName: 'You',
    text: "That works great. I'll be there by 6:25 👍",
    sentAt: new Date().toISOString(),
  },
  {
    id: 'm3',
    rideId: 'r1',
    senderId: 'u1',
    senderName: 'Sarah Mitchell',
    text: 'Perfect, see you then! Silver Camry, plate ends 42K.',
    sentAt: new Date().toISOString(),
  },
];

function nextDayAt(time: string): string {
  const [hours, mins] = time.split(':').map(Number);
  const d = new Date();
  d.setDate(d.getDate() + 1);
  d.setHours(hours, mins, 0, 0);
  return d.toISOString();
}
